# Generated by Django 4.2.13 on 2024-11-11 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='medium',
            field=models.ManyToManyField(to='interactions.broadcastmedium'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='receivers',
            field=models.ManyToManyField(related_name='received_broadcast_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_broadcast_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
