# Generated by Django 4.2.13 on 2024-11-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resultsFramework', '0001_initial'),
        ('masterReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_quarters', to='resultsFramework.quarter'),
        ),
    ]
