# Generated by Django 4.2.13 on 2024-11-11 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterReport', '0002_initial'),
        ('userManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultsFramework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='report_guideline',
            field=models.ManyToManyField(blank=True, to='masterReport.reportguideline'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultsFramework.year'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterReport.report'),
        ),
        migrations.AddField(
            model_name='reportguideline',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_report_quarters', to='resultsFramework.quarter'),
        ),
        migrations.AddField(
            model_name='report',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterReport.reporttype'),
        ),
        migrations.AddField(
            model_name='report',
            name='responsible_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.responsibleministry'),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultsFramework.year'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_master_report_quarters', to='resultsFramework.quarter'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterReport.reporttype'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='responsible_ministry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.responsibleministry'),
        ),
        migrations.AddField(
            model_name='masterreport',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultsFramework.year'),
        ),
        migrations.AlterUniqueTogether(
            name='masterreport',
            unique_together={('quarter', 'year', 'responsible_ministry')},
        ),
    ]
