# Generated by Django 4.2.13 on 2024-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleministry',
            name='affiliated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.responsibleministry'),
        ),
        migrations.AddField(
            model_name='responsibleministry',
            name='is_affiliated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
