# Generated by Django 4.2.13 on 2024-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleministry',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsibleministry',
            name='visible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
