# Generated by Django 4.2.13 on 2024-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleministry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ministryImage'),
        ),
    ]
