# Generated by Django 4.2.13 on 2024-11-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_responsibleministry_affiliated_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.responsibleministry')),
            ],
        ),
    ]
