# Generated by Django 4.2.13 on 2024-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyarea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
