# Generated by Django 4.2.13 on 2024-11-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0003_policyarea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualplan',
            name='validation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
