# Generated by Django 4.2.13 on 2024-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0007_alter_policyarea_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicgoal',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
