# Generated by Django 4.2.13 on 2024-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0008_strategicgoal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicgoal',
            name='goal_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
