# Generated by Django 4.2.13 on 2024-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0009_alter_strategicgoal_goal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyarea',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
