# Generated by Django 4.2.13 on 2024-11-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0014_keyresultarea_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresultarea',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
