# Generated by Django 4.2.13 on 2024-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0016_alter_keyresultarea_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
