# Generated by Django 4.2.13 on 2024-11-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultsFramework', '0006_annualplan_validated'),
        ('resultsFramework', '0017_indicator_code'),
    ]

    operations = [
    ]
