# Generated by Django 4.2.13 on 2024-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0002_responsibleministry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200)),
                ('name_amh', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200)),
                ('name_amh', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name_eng', models.CharField(max_length=100)),
                ('kpi_name_amh', models.CharField(blank=True, max_length=100)),
                ('kpi_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('kpi_measurement_units', models.CharField(max_length=50)),
                ('kpi_characteristics', models.CharField(choices=[('inc', 'Increasing'), ('dec', 'Decreasing'), ('const', 'Constant')], default='inc', max_length=10)),
            ],
            options={
                'verbose_name': 'Key Performance Indicator',
            },
        ),
        migrations.CreateModel(
            name='KpiAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_kpi_name_eng', models.CharField(max_length=400)),
                ('sub_kpi_name_amh', models.CharField(max_length=400)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.category')),
                ('kpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_kpi', to='DashboardApp.indicator')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='DashboardApp.kpiaggregation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amh', models.CharField(blank=True, max_length=100, null=True)),
                ('month_english', models.CharField(blank=True, max_length=100, null=True)),
                ('month_ranked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NationalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np_name_eng', models.CharField(blank=True, max_length=150)),
                ('np_name_amh', models.CharField(blank=True, max_length=150)),
                ('description_eng', models.TextField()),
                ('description_amh', models.TextField()),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('quarter_amharic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_eng', models.IntegerField(blank=True, null=True)),
                ('year_amh', models.IntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['year_amh'],
            },
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name_eng', models.CharField(blank=True, max_length=350)),
                ('goal_name_amh', models.CharField(blank=True, max_length=350, null=True)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('goal_is_shared', models.BooleanField(default=False)),
                ('national_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.nationalplan')),
                ('responsible_ministries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_goal', to='userManagement.responsibleministry')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_target', models.FloatField(blank=True)),
                ('quarter_performance', models.FloatField(blank=True, null=True)),
                ('quarter_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter_indicators', to='DashboardApp.indicator')),
                ('national_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.nationalplan')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='DashboardApp.quarter')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
        migrations.AddField(
            model_name='quarter',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.year'),
        ),
        migrations.CreateModel(
            name='MonthProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_target', models.FloatField(blank=True)),
                ('month_performance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_indicators', to='DashboardApp.indicator')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='DashboardApp.month')),
                ('national_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.nationalplan')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.year'),
        ),
        migrations.CreateModel(
            name='KeyResultArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name_eng', models.CharField(max_length=350)),
                ('activity_name_amh', models.CharField(blank=True, max_length=350)),
                ('activity_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activity_is_shared', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kra_goal', to='DashboardApp.strategicgoal', verbose_name='Strategic Planning Goals')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='keyResultArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.keyresultarea'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='responsible_ministries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.responsibleministry'),
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('performance', models.BooleanField(blank=True, null=True)),
                ('target', models.BooleanField(blank=True, null=True)),
                ('indicator', models.ManyToManyField(to='DashboardApp.indicator')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.month')),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.quarter')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
            options={
                'ordering': ['year__year_amh'],
            },
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_target', models.FloatField(blank=True, null=True)),
                ('annual_performance', models.FloatField(blank=True, null=True)),
                ('annual_date', models.DateTimeField(auto_now_add=True)),
                ('target_state', models.CharField(choices=[('cum', 'Cumulative'), ('net', 'Net')], max_length=20, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_indicators', to='DashboardApp.indicator')),
                ('national_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.nationalplan')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
        migrations.AddIndex(
            model_name='keyresultarea',
            index=models.Index(fields=['goal'], name='DashboardAp_goal_id_9f7360_idx'),
        ),
    ]
