# Generated by Django 5.0.6 on 2024-06-01 13:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200)),
                ('name_amh', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('quarter_amharic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_eng', models.IntegerField()),
                ('year_amh', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['year_amh'],
            },
        ),
        migrations.CreateModel(
            name='KpiAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_kpi_name_eng', models.CharField(max_length=400)),
                ('sub_kpi_name_amh', models.CharField(max_length=400)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.category')),
                ('kpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_kpi', to='DashboardApp.indicator')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='DashboardApp.kpiaggregation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amh', models.CharField(max_length=100)),
                ('month_english', models.CharField(max_length=100)),
                ('month_ranked', models.IntegerField()),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_target', models.FloatField(blank=True)),
                ('quarter_performance', models.FloatField(blank=True, null=True)),
                ('quarter_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter_indicators', to='DashboardApp.indicator')),
                ('national_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.nationalplan')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='DashboardApp.quarter')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
        migrations.CreateModel(
            name='MonthProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_target', models.FloatField(blank=True)),
                ('month_performance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_indicators', to='DashboardApp.indicator')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='DashboardApp.month')),
                ('national_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.nationalplan')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_target', models.FloatField(blank=True, null=True)),
                ('annual_performance', models.FloatField(blank=True, null=True)),
                ('annual_date', models.DateTimeField(auto_now_add=True)),
                ('target_state', models.CharField(choices=[('cum', 'Cumulative'), ('net', 'Net')], max_length=20, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_indicators', to='DashboardApp.indicator')),
                ('national_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.nationalplan')),
                ('sub_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_sub_indicators', to='DashboardApp.kpiaggregation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year')),
            ],
        ),
    ]
