# Generated by Django 4.2.13 on 2024-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_sdg_policyarea_goal_policyarea_sdg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdg',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
