# Generated by Django 4.2.13 on 2024-06-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_remove_month_year_remove_quarter_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.quarter'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_amh',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_amh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_eng',
            field=models.IntegerField(),
        ),
    ]
