# Generated by Django 4.2.13 on 2024-06-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_category_quarter_year_kpiaggregation_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='trend_type',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='view_type',
        ),
        migrations.RemoveField(
            model_name='month',
            name='quarter',
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.year'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardApp.year'),
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='indicator',
        ),
        migrations.AlterField(
            model_name='month',
            name='month_amh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_amh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_eng',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='indicator',
            field=models.ManyToManyField(to='DashboardApp.indicator'),
        ),
    ]
