# Generated by Django 4.2.13 on 2024-06-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_alter_indicator_keyresultarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='keyResultArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='DashboardApp.keyresultarea'),
        ),
    ]
