# Generated by Django 4.2.13 on 2024-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_remove_dashboardsetting_trend_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
