# Generated by Django 4.2.13 on 2024-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_month_quarter_alter_month_month_amh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
