# Generated by Django 4.2.13 on 2024-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_alter_indicator_kpi_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='kpi_measurement_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
