# Generated by Django 4.2.13 on 2024-06-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_dashboardsetting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='dashboard_category',
        ),
    ]
