# Generated by Django 4.2.13 on 2024-06-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_dashboardsetting_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardsetting',
            options={'ordering': ['rank']},
        ),
    ]
