# Generated by Django 4.2.13 on 2024-10-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_alter_sdg_options_alter_sdg_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyarea',
            name='goal',
        ),
        migrations.AlterField(
            model_name='policyarea',
            name='sdg',
            field=models.ManyToManyField(blank=True, to='DashboardApp.sdg'),
        ),
    ]
