# Generated by Django 4.2.13 on 2024-06-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_remove_dashboardsetting_dashboard_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthprogress',
            old_name='monthly_target',
            new_name='month_target',
        ),
    ]
