# Generated by Django 4.2.13 on 2024-06-03 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_remove_dashboardsetting_dashboard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsetting',
            name='indicator',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardApp.indicator'),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.month'),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='performance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.quarter'),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='target',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
