# Generated by Django 4.2.13 on 2024-06-03 16:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_alter_dashboardsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCardRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('starting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ending', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
