# Generated by Django 4.2.13 on 2024-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_remove_policyarea_goal_alter_policyarea_sdg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYDPSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('sdg', models.ManyToManyField(blank=True, to='DashboardApp.sdg')),
            ],
        ),
    ]
