# Generated by Django 4.2.13 on 2024-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_scorecardrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='is_score_card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='performance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='target',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
