# Generated by Django 4.2.13 on 2024-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_alter_dashboardsetting_indicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsetting',
            name='performance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='target',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
