# Generated by Django 4.2.13 on 2024-10-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_tydpsectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TYDPSectors',
            new_name='AgendaGoals',
        ),
    ]
