# Generated by Django 4.2.13 on 2024-10-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_rename_tydpsectors_agendagoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendagoals',
            name='sdg',
            field=models.ManyToManyField(blank=True, related_name='agenda_goals', to='DashboardApp.sdg'),
        ),
    ]
